<center><h3>Numpy Fundaments form IIT Nepal</h3></center>
<img src="https://iitnepal.edu.np/wp-content/themes/iit/images/logo-colorful.svg" style="height:100px;width:auto;">
<center><h4>Contact us: 9851161198/9851224985 different IT professional program in this pandemic throguh online in 50% discount</h4></center>

In [2]:
import numpy as np

In [4]:
np.empty((2,2,2))

array([[[5.11798224e-307, 3.44897992e-307],
        [1.69118108e-306, 9.34609790e-307]],

       [[6.23037657e-307, 9.34596889e-307],
        [8.90060780e-307, 3.49699467e-317]]])

In [5]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [7]:
np.arange(2,10,1)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(10,2,-2)

array([10,  8,  6,  4])

In [9]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [17]:
np.random.rand(3,2,1)

array([[[0.01336947],
        [0.9125229 ]],

       [[0.70322332],
        [0.65917593]],

       [[0.22877922],
        [0.21460896]]])

### initialization

In [28]:
a = np.random.randint(0,10,size=(5,5))

In [30]:
a

array([[1, 1, 0, 9, 6],
       [6, 5, 3, 3, 8],
       [6, 0, 3, 0, 6],
       [3, 4, 4, 2, 5],
       [8, 7, 5, 0, 5]])

### Access

In [31]:
a[:,:]

array([[1, 1, 0, 9, 6],
       [6, 5, 3, 3, 8],
       [6, 0, 3, 0, 6],
       [3, 4, 4, 2, 5],
       [8, 7, 5, 0, 5]])

In [45]:
a[[0,4,2],:]

array([[1, 1, 0, 9, 6],
       [8, 7, 5, 0, 5],
       [6, 0, 3, 0, 6]])

In [32]:
a[0,:]

array([1, 1, 0, 9, 6])

In [38]:
a[:,:3]

array([[1, 1, 0],
       [6, 5, 3],
       [6, 0, 3],
       [3, 4, 4],
       [8, 7, 5]])

In [33]:
a[:,0]

array([1, 6, 6, 3, 8])

In [39]:
a[:,1:4]

array([[1, 0, 9],
       [5, 3, 3],
       [0, 3, 0],
       [4, 4, 2],
       [7, 5, 0]])

In [41]:
a[:,1]

array([1, 5, 0, 4, 7])

In [42]:
a[1:4,1:4]

array([[5, 3, 3],
       [0, 3, 0],
       [4, 4, 2]])

### Concatenation

In [43]:
a

array([[1, 1, 0, 9, 6],
       [6, 5, 3, 3, 8],
       [6, 0, 3, 0, 6],
       [3, 4, 4, 2, 5],
       [8, 7, 5, 0, 5]])

In [46]:
b = np.random.randint(0,5,size=(5,5))

In [47]:
b

array([[2, 1, 1, 1, 2],
       [4, 3, 0, 2, 2],
       [0, 4, 2, 1, 3],
       [4, 2, 0, 1, 0],
       [0, 1, 2, 2, 3]])

In [48]:
np.vstack([a,b])

array([[1, 1, 0, 9, 6],
       [6, 5, 3, 3, 8],
       [6, 0, 3, 0, 6],
       [3, 4, 4, 2, 5],
       [8, 7, 5, 0, 5],
       [2, 1, 1, 1, 2],
       [4, 3, 0, 2, 2],
       [0, 4, 2, 1, 3],
       [4, 2, 0, 1, 0],
       [0, 1, 2, 2, 3]])

In [49]:
np.hstack([a,b])

array([[1, 1, 0, 9, 6, 2, 1, 1, 1, 2],
       [6, 5, 3, 3, 8, 4, 3, 0, 2, 2],
       [6, 0, 3, 0, 6, 0, 4, 2, 1, 3],
       [3, 4, 4, 2, 5, 4, 2, 0, 1, 0],
       [8, 7, 5, 0, 5, 0, 1, 2, 2, 3]])

### Splitting

In [50]:
a

array([[1, 1, 0, 9, 6],
       [6, 5, 3, 3, 8],
       [6, 0, 3, 0, 6],
       [3, 4, 4, 2, 5],
       [8, 7, 5, 0, 5]])

In [59]:
x,y = np.hsplit(a,[2])

In [60]:
x

array([[1, 1],
       [6, 5],
       [6, 0],
       [3, 4],
       [8, 7]])

In [61]:
y

array([[0, 9, 6],
       [3, 3, 8],
       [3, 0, 6],
       [4, 2, 5],
       [5, 0, 5]])

In [64]:
a[1,:]

array([6, 5, 3, 3, 8])

### Shape, Size, ndim

In [66]:
a.ndim

2

In [67]:
a.shape

(5, 5)

In [68]:
a.size

25

### Reshaping

In [69]:
x = np.random.randint(1,15,size=(5,4))

In [70]:
x

array([[ 2, 10,  2,  7],
       [ 4,  9,  1, 14],
       [ 4, 10,  2,  9],
       [12,  8, 14,  8],
       [10,  3,  2, 13]])

In [71]:
x.shape

(5, 4)

In [75]:
x = x.reshape(10,2)

In [78]:
x.reshape(5,4)

array([[ 2, 10,  2,  7],
       [ 4,  9,  1, 14],
       [ 4, 10,  2,  9],
       [12,  8, 14,  8],
       [10,  3,  2, 13]])

In [ ]:
x.shape

### utility function

In [79]:
a

array([[1, 1, 0, 9, 6],
       [6, 5, 3, 3, 8],
       [6, 0, 3, 0, 6],
       [3, 4, 4, 2, 5],
       [8, 7, 5, 0, 5]])

In [80]:
a.max()

9

In [82]:
a.max()

9

In [ ]:
np.max(a)

In [83]:
a.min()

0

In [86]:
np.min(a)

0

In [84]:
a.mean()

4.0

In [87]:
a.std()

2.6532998322843198

In [94]:
np.all(a>=0)

True

In [ ]:
np.any(a>3)

In [92]:
np.any(a>9)

False

In [ ]:
a

In [ ]:
b

In [95]:
a.dot(b)

array([[42, 28, 13, 24, 22],
       [44, 47, 28, 38, 55],
       [12, 24, 24, 21, 39],
       [30, 40, 21, 27, 41],
       [44, 54, 28, 37, 60]])

In [96]:
np.multiply(a,b)

array([[ 2,  1,  0,  9, 12],
       [24, 15,  0,  6, 16],
       [ 0,  0,  6,  0, 18],
       [12,  8,  0,  2,  0],
       [ 0,  7, 10,  0, 15]])

In [99]:
a*b

array([[ 2,  1,  0,  9, 12],
       [24, 15,  0,  6, 16],
       [ 0,  0,  6,  0, 18],
       [12,  8,  0,  2,  0],
       [ 0,  7, 10,  0, 15]])

In [101]:
a.dot(b)

array([[42, 28, 13, 24, 22],
       [44, 47, 28, 38, 55],
       [12, 24, 24, 21, 39],
       [30, 40, 21, 27, 41],
       [44, 54, 28, 37, 60]])

In [102]:
np.sqrt(25)

5.0

In [103]:
a

array([[1, 1, 0, 9, 6],
       [6, 5, 3, 3, 8],
       [6, 0, 3, 0, 6],
       [3, 4, 4, 2, 5],
       [8, 7, 5, 0, 5]])

In [104]:
np.sqrt(a)

array([[1.        , 1.        , 0.        , 3.        , 2.44948974],
       [2.44948974, 2.23606798, 1.73205081, 1.73205081, 2.82842712],
       [2.44948974, 0.        , 1.73205081, 0.        , 2.44948974],
       [1.73205081, 2.        , 2.        , 1.41421356, 2.23606798],
       [2.82842712, 2.64575131, 2.23606798, 0.        , 2.23606798]])

#### Broadcasting

In [105]:
y = np.random.randint(1,5,size=(2,2))

In [106]:
y

array([[4, 3],
       [1, 4]])

In [107]:
y=y*2

In [108]:
y

array([[8, 6],
       [2, 8]])

In [110]:
y[y>5]=5

In [111]:
y

array([[5, 5],
       [2, 5]])